### PR TITLE
Update Java API

### PR DESCRIPTION
**Pull request by ZheSun88**
update generated file

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout-flow/18)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java, line 272 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18#-L4FEyPF1Gx46icp6e0L:-L4FEyPF1Gx46icp6e0M:b-w1ylvg) ([raw file](https://github.com/vaadin/vaadin-split-layout-flow/blob/894af98d8976be3c7df158e4cc401843145bbf96/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java#L272)):*
> protected Registration addSplitterDragendListener(

Shouldn't be exposed as a public API in subclass ?

---

*[src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java, line 292 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18#-L4FF1SR4hg-x1b-FSRJ:-L4FF1SR4hg-x1b-FSRK:b-dygg7) ([raw file](https://github.com/vaadin/vaadin-split-layout-flow/blob/894af98d8976be3c7df158e4cc401843145bbf96/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java#L292)):*
> protected R addToPrimary(Component... components) {

Shouldn't be exposed as public API?

---

*[src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java, line 314 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18#-L4FF4h_S8gN7YJn6Fc6:-L4FF4h_S8gN7YJn6Fc7:biaop9n) ([raw file](https://github.com/vaadin/vaadin-split-layout-flow/blob/894af98d8976be3c7df158e4cc401843145bbf96/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java#L314)):*
> protected R addToSecondary(Component... components) {

Shouldn't be exposed as public API?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18)*

**Comment by ZheSun88** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java, line 272 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18#-L4FEyPF1Gx46icp6e0L:-L4FFwza4A6wB_IDJNJ8:bfu5k7x) ([raw file](https://github.com/vaadin/vaadin-split-layout-flow/blob/894af98d8976be3c7df158e4cc401843145bbf96/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java#L272)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> protected Registration addSplitterDragendListener(

Shouldn't be exposed as a public API in subclass ?
</blockquote></details>

added. 

---

*[src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java, line 292 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18#-L4FF1SR4hg-x1b-FSRJ:-L4FG90Cko5SjGvWSY6I:bowrisw) ([raw file](https://github.com/vaadin/vaadin-split-layout-flow/blob/894af98d8976be3c7df158e4cc401843145bbf96/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java#L292)):*
>  public SplitLayout addToPrimary(Component... components) {
this has already been added, right?

---

*[src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java, line 314 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18#-L4FF4h_S8gN7YJn6Fc6:-L4FGHFgtF0gH5vdmAwr:brgubzh) ([raw file](https://github.com/vaadin/vaadin-split-layout-flow/blob/894af98d8976be3c7df158e4cc401843145bbf96/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java#L314)):*
> public SplitLayout addToSecondary(Component... components) 
This has already been added, too, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18)*

**Comment by denis-anisimov** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java, line 292 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18#-L4FF1SR4hg-x1b-FSRJ:-L4FHH8wIpuM2XW4QCcA:bmp5nu5) ([raw file](https://github.com/vaadin/vaadin-split-layout-flow/blob/894af98d8976be3c7df158e4cc401843145bbf96/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java#L292)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

>  public SplitLayout addToPrimary(Component... components) {
this has already been added, right?
</blockquote></details>

Right, missed that.

---

*[src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java, line 314 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18#-L4FF4h_S8gN7YJn6Fc6:-L4FHJQUlPzBanOLWv-R:b-7d2mb1) ([raw file](https://github.com/vaadin/vaadin-split-layout-flow/blob/894af98d8976be3c7df158e4cc401843145bbf96/src/main/java/com/vaadin/flow/component/splitlayout/GeneratedVaadinSplitLayout.java#L314)):*
> Right, missed that.
Right, missed that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/18)*

**Pull request merged**
