### PR TITLE
Update generated code

### PR DESCRIPTION
**Pull request by ZheSun88**
fix after vaadin/flow#3678

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-split-layout-flow/24)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-split-layout-flow/24)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-split-layout-flow/24#-:-L7YaoP51oLa0JpcdGiF:bnfp4nl)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-split-layout-flow/24#-L7Z3wol2hxAxMVzfgpD:-L7Z3wol2hxAxMVzfgpE:b-pf2nip) (no related file):*
Could you add a Junit test to this that checks that any component element added to the layout actually gets the "slot" attribute "primary" or "secondary" according to where we add the component.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-split-layout-flow/24)*

**Comment by ZheSun88** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-split-layout-flow/24#-L7Z3wol2hxAxMVzfgpD:-L7ZDXBAAHCCNb_kOpVl:btlx526) (no related file):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Could you add a Junit test to this that checks that any component element added to the layout actually gets the "slot" attribute "primary" or "secondary" according to where we add the component.
</blockquote></details>

Yes. added

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-split-layout-flow/24)*

**Comment by caalador** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-split-layout-flow/24#-:-L7ZFeD82X0msCXFIQqG:bnfp4nl)*

**Pull request merged**
